"""unique keys

Revision ID: 3f9d3c9640c6
Revises: b9f52d096713
Create Date: 2025-04-19 17:25:54.501586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3f9d3c9640c6'
down_revision: Union[str, None] = 'b9f52d096713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tb_users', ['username'])
    op.create_unique_constraint(None, 'tb_users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_users', type_='unique')
    op.drop_constraint(None, 'tb_users', type_='unique')
    # ### end Alembic commands ###
