"""embrapa table

Revision ID: 8957a17f71ce
Revises: 3f9d3c9640c6
Create Date: 2025-04-20 13:35:26.214769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8957a17f71ce'
down_revision: Union[str, None] = '3f9d3c9640c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_viticulture',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('subcategory', sa.VARCHAR(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_viticulture')
    # ### end Alembic commands ###
